# Generated by Django 5.1.1 on 2024-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comid', models.IntegerField()),
                ('comname', models.CharField(max_length=50)),
                ('noofemps', models.IntegerField()),
                ('comaddr', models.CharField(max_length=50)),
            ],
        ),
    ]
