# Generated by Django 5.1.1 on 2024-09-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBModelApp', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comaddr',
            new_name='compaddr',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comid',
            new_name='compid',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comname',
            new_name='compname',
        ),
    ]
